version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  alice:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: alice
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - IIOS_SERVER_PORT=20991
      - PUBSUB_RPC=${PUBSUB_RPC}
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_NAMESPACE=testings
      - REDIS_HOST=redis
      - DEBUG=iios:*
    command: ["pm2-docker", "test/gateway/index.js"]

  bob:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: bob
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - SERVICE_NAME=bob
      - PUBSUB_RPC=${PUBSUB_RPC}
      - IIOS_SERVER_PORT=20992
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_NAMESPACE=testings
      - REDIS_HOST=redis
      - DEBUG=iios:*
    command: ["./test/service/delayed_start.sh", "2"]

  ted:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: ted
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - SERVICE_NAME=ted
      - IIOS_SERVER_PORT=20993
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_NAMESPACE=testings
      - REDIS_HOST=redis
      - DEBUG=iios:*
    command: ["./test/service/delayed_start.sh", "15"]
