version: '3.3'

services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  alice:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: alice
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - IIOS_SERVER_PORT=20991
      - PUBSUB_RPC=${PUBSUB_RPC}
      - ENCODER=${ENCODER}
      - BINDING=${BINDING}
      - STREAMING=${STREAMING}
      - IIOS_SERVER_HOST=alice
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - REDIS_HOST=redis
      - DEBUG=${DEBUG}
    command: ["node", "test/gateway/index.js"]

  bob:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: bob
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - SERVICE_NAME=bob
      - PUBSUB_RPC=${PUBSUB_RPC}
      - ENCODER=${ENCODER}
      - BINDING=${BINDING}
      - STREAMING=${STREAMING}
      - IIOS_OUTPUT_EVENTS=${IIOS_OUTPUT_EVENTS}
      - IIOS_SERVER_PORT=20992
      - IIOS_SERVER_HOST=bob
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - REDIS_HOST=redis
      - DEBUG=${DEBUG}
      - DELAYED=2
    command: ["node", "test/service/index.js"]

  ted:
    image: ignitial/iios:latest
    depends_on:
      - redis
    container_name: ted
    volumes:
      - ${PWD}:/opt/svc
    environment:
      - SERVICE_NAME=ted
      - PUBSUB_RPC=${PUBSUB_RPC}
      - ENCODER=${ENCODER}
      - BINDING=${BINDING}
      - STREAMING=${STREAMING}
      - IIOS_SERVER_PORT=20993
      - IIOS_SERVER_HOST=ted
      - IIOS_NAMESPACE=${IIOS_NAMESPACE}
      - REDIS_HOST=redis
      - DEBUG=${DEBUG}
      - DELAYED=15
    command: ["node", "test/service/index.js", "15"]

volumes:
  redis-data:
